<!DOCTYPE html>
<html>
    <head>
        <title>Promise Error Handling</title>
    </head>
    <body>
        <script>
            //--------------------------------example 1
            // function getUserById(id) {
            //  return new Promise((resolve, reject) => {
            //     resolve({
            //       id: id,
            //       username: 'admin'
            //     });
            //  });
            // }
            
            //-------------------------------------------example 2

        //     function getUserById(id) {
        //     if (typeof id !== 'number' || id <= 0) {
        //            throw new Error('Invalid id argument');
        //     }

        //       return new Promise((resolve, reject) => {
        //                resolve({
        //                   id: id,
        //                   username: 'admin'
        //                 });
        //       });
        //     }
        // //     getUserById('a')
        // //    .then(user => console.log(user.username))
        // //    .catch(err => console.log(err));

        //    try {
        //     getUserById('a')
        //     .then(user => console.log(user.username))
        //     .catch(err => console.log(`Caught by .catch ${error}`));
        //   } catch (error) {
        //     console.log(`Caught by try/catch ${error}`);
        //   }

        //-----------------------------------------example 3 
    //     let authorized = false;

    //     function getUserById(id) {
    //           return new Promise((resolve, reject) => {
    //                      if (!authorized) {
    //                          throw new Error('Unauthorized access to the user data');
    //                      }
    //           resolve({
    //                      id: id,
    //                      username: 'admin'
    //          });
    //          });
    //     }
    //     try {
    //          getUserById(10)
    //         .then(user => console.log(user.username))
    //         .catch(err => console.log(`Caught by .catch ${error}`));
    //     } catch (error) {
    //           console.log(`Caught by try/catch ${error}`);
    //     }
    //     promise1
    // .then(promise2)
    // .then(promise3)
    // .then(promise4)
    // .catch(err => console.log(err));

    //--------------------------------------------------------example 4
//     let authorized = false;

// function getUserById(id) {
//     return new Promise((resolve, reject) => {
//         if (!authorized) {
//             reject('Unauthorized access to the user data');
//         }

//         resolve({
//             id: id,
//             username: 'admin'
//         });
//     });
// }

// try {
//     getUserById(10)
//         .then(user => console.log(user.username))
//         .catch(err => console.log(`Caught by .catch ${err}`));
// } catch (error) {
//     console.log(`Caught by try/catch ${error}`);
// }

//---------------------------------------------------------example 5 
function getUserById(id) {
    return new Promise((resolve, reject) => {
        if (!authorized) {
            reject('Unauthorized access to the user data');
        }
        resolve({
            id: id,
            username: 'admin'
        });
    });
}

try {
    getUserById(10)
        .then(user => console.log(user.username));
    // the following code will not execute
    console.log('next');

} catch (error) {
    console.log(`Caught by try/catch ${error}`);
}

        </script>
    </body>
</html>